spring.application.name=LightWeightCP

spring.datasource.url=jdbc:postgresql://localhost:5432/lightweightcp
# TODO change username and password
#spring.datasource.username=postgres
spring.datasource.username=grainneshannon
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.boot.autoconfigure=DEBUG